pipeline:
  build:
    group: build
    image: golang:latest
    environment:
      - NAME=testing
    commands:
      - go build
      - telnet localhost 5432
services:
  postgres:
    image: postgres
    
