pipeline:
  build:
    group: build
    image: golang:latest
    environment:
      - NAME=testing
    commands:
      - go build
      - go test
      
services:
  postgres:
    image: postgres
    
